"""Builds build_deck_ua.js from build_deck.js by exact-string translation (fails loudly on any miss)."""
s = open('build_deck.js', encoding='utf8').read()
R = [
 ('pres.title = "DICEUS - SEO & AI Search plan";', 'pres.title = "DICEUS - план SEO та AI-пошуку";'),
 ('pres.author = "Senior Technical SEO & AI Search candidate";', 'pres.author = "Кандидат на позицію Senior Technical SEO & AI Search";'),
 ('"DICEUS · SEO & AI Search plan · confidential"', '"DICEUS · план SEO та AI-пошуку · конфіденційно"'),
 # 1
 ('"From dev shop to insurance software vendor"', '"Від аутсорс-студії до вендора страхового ПЗ"'),
 ('"SEO & AI Search plan for diceus.com: why the site underperforms the product strategy, what to change, and the 90-day plan"', '"План SEO та AI-пошуку для diceus.com: чому сайт не працює на продуктову стратегію, що змінити, і план на 90 днів"'),
 ('"Evidence: own crawl of 815 URLs · 44 SERPs · 20-prompt AI panel · 13 competitors · 7 pivot case studies   |   October 2026"', '"Докази: власний краул 815 URL · 44 видачі · AI-панель з 20 запитів · 13 конкурентів · 7 кейсів півоту   |   жовтень 2026"'),
 ('"Purpose: agree the direction and the first 30 days. Everything shown is from public data; GSC, GA4 and CRM were not available and are marked as such in the full deliverables (01-06)."', '"Мета: погодити напрям і перші 30 днів. Усі дані публічні; доступу до GSC, GA4 і CRM не було — це позначено в повних матеріалах (01-06)."'),
 # 2
 ('"The answer on one slide"', '"Відповідь на одному слайді"'),
 ('"Change the weight, not the URLs: fix, reposition, then win alternative risk first"', '"Змінюємо вагу, а не URL: виправити, перепозиціонувати, першими виграти alternative risk"'),
 ('''"Pyramid: main message first. 1) A free fix protects the only territory where DICEUS already wins. 2) The site and entity still say 'dev shop'; repositioning is done through homepage, navigation, links and schema - no URL migration. 3) Alternative risk is the highest relevance x feasibility territory; build it as the first complete product cluster with real proof."''',
  '''"Піраміда: головне — спочатку. 1) Безкоштовне виправлення захищає єдину територію, де DICEUS уже виграє. 2) Сайт і сутність бренду досі кажуть «аутсорс»; перепозиціонування — через головну, навігацію, посилання та schema, без міграції URL. 3) Alternative risk — територія з найвищою релевантністю × досяжністю; будуємо її як перший повний продуктовий кластер зі справжніми доказами."'''),
 ('"Fix this week", "3 product pages are noindexed, including Captive Management and RRG: the pages where DICEUS already wins in search and AI answers", "Remove stray tag · deploy guardrail"',
  '"Виправити цього тижня", "3 продуктові сторінки закриті noindex, серед них Captive Management і RRG — саме ті, де DICEUS уже виграє в пошуку та AI-відповідях", "Прибрати зайвий тег · захист при деплої"'),
 ('"Reposition: days 1-60", "Homepage, navigation and internal links still sell custom development. Make products the strongest pages, keep services as a secondary line", "Homepage · nav · links · schema"',
  '"Перебудова: дні 1-60", "Головна, навігація та внутрішні посилання досі продають розробку на замовлення. Зробити продукти найсильнішими сторінками, послуги — другою лінією", "Головна · меню · посилання · schema"'),
 ('"Win alt-risk: days 1-90", "Captive and RRG software is winnable now: DICEUS is #1 in our sample and no vendor owns the category. Add proof, buyer assets and AI-ready facts", "Hub · proof · reviews · comparisons"',
  '"Alt-risk: дні 1-90", "ПЗ для captive і RRG можна виграти вже зараз: DICEUS №1 у нашій вибірці, категорію ніхто не займає. Додати докази, матеріали для покупців і факти для AI", "Хаб · докази · відгуки · порівняння"'),
 # 3
 ('"Today the site tells Google, buyers and AI: \\"dev shop\\""', '"Сьогодні сайт каже Google, покупцям і AI: «аутсорс»"'),
 ('"Five measured symptoms (own crawl and panels, 6 Oct 2026)"', '"П\'ять виміряних симптомів (власний краул і панелі, 6 жовтня 2026)"'),
 ('"Sources: crawl of 815 URLs (02_Current_State_Audit.xlsx Summary, Layer_Links, Indexability); AI panel (03 AI_Panel). Contextual links exclude the ~300 sitewide mega-menu links. AI panel = Claude with web search, 1 run per prompt, directional."',
  '"Джерела: краул 815 URL (02_Current_State_Audit.xlsx: Summary, Layer_Links, Indexability); AI-панель (03 AI_Panel). Контекстні посилання — без ~300 посилань мегаменю на кожній сторінці. AI-панель = Claude з веб-пошуком, 1 прогін на запит, орієнтовно."'),
 ('"product pages vs generic service, expertise and non-insurance industry pages"', '"продуктових сторінок проти сторінок загальних послуг, експертиз і нестрахових галузей"'),
 ('"median in-content links a product page gets vs a generic service page"', '"медіана посилань у тексті на продуктову сторінку проти сторінки загальної послуги"'),
 ('"product pages excluded by noindex: Captive Mgmt, RRG, Group Health"', '"продуктові сторінки виключені noindex: Captive Mgmt, RRG, Group Health"'),
 ('"unbranded AI prompts that name DICEUS (captive and RRG only)"', '"небрендових AI-запитів, де названо DICEUS (лише captive і RRG)"'),
 ('"product pages with product schema; 0 reviews on product listings"', '"продуктових сторінок мають product schema; 0 відгуків у продуктових лістингах"'),
 ('"Homepage H1"', '"H1 головної"'),
 ('"last modified 2022 · 0.99 title match with a services page"', '"оновлено 2022 · збіг title 0,99 зі сторінкою послуги"'),
 # 4
 ('"The homepage tells the agency story first"', '"Головна розповідає спершу історію агенції"'),
 ('"Current H2 order (crawl) vs proposed order: products, segments and proof first, services as one strip"', '"Поточний порядок H2 (краул) проти запропонованого: спершу продукти, сегменти й докази, послуги — одним блоком"'),
 ('''"Current H2 sequence taken verbatim from the crawl. Proposed: title 'DICEUS - Insurance Software for Carriers, MGAs & Captives'; H1 'Insurance software products for carriers, MGAs and alternative risk'. Staged change: first hand the generic 'custom software development company' query to /services/custom-software-development/, check GSC, then retitle the homepage (rollback ready)."''',
  '''"Поточні H2 взято дослівно з краулу (сайт англомовний, тому ліва колонка — оригінал). Пропозиція: title 'DICEUS - Insurance Software for Carriers, MGAs & Captives'; H1 'Insurance software products for carriers, MGAs and alternative risk'. Поетапно: спершу передати загальний запит 'custom software development company' сторінці /services/custom-software-development/, перевірити GSC, потім змінити title головної (з планом відкату)."'''),
 ('const next = ["H1: Insurance software for carriers, MGAs & alt-risk", "Choose your path: captives · RRGs · MGAs · carriers", "Product families: core, distribution, finance & data, alternative risk", "Proof band: named outcomes, VCIA partner, product reviews", "How we deliver: implementation in weeks, security & trust", "Services strip: implementation, modernization, custom dev", "Insights: captive, RRG and PAS guides", "Book a demo"];',
  'const next = ["H1: страхове ПЗ для страховиків, MGA та alt-risk", "Оберіть шлях: captive · RRG · MGA · страховики", "Родини продуктів: core, дистрибуція, фінанси, alt-risk", "Смуга доказів: результати, партнер VCIA, відгуки", "Як впроваджуємо: тижні, безпека й довіра", "Блок послуг: впровадження, модернізація, розробка", "Експертиза: гайди про captive, RRG і PAS", "Замовити демо"];'),
 ('[["NOW", now, CORAL, 0.6], ["PROPOSED", next, TEAL, 6.8]]', '[["ЗАРАЗ (дослівно з сайту)", now, CORAL, 0.6], ["ПРОПОНУЄМО", next, TEAL, 6.8]]'),
 # 5
 ('"Product pages lose on proof, not on features"', '"Продукти програють на доказах, а не на функціях"'),
 ('"DICEUS has the deepest captive feature content in the set, but none of the trust signals buyers and AI look for"', '"У DICEUS найглибший опис функцій для captive, але немає сигналів довіри, які шукають покупці та AI"'),
 ('''"Competitor teardown (data/competitor_teardown.md): Luzern Risk (4 anonymised testimonials with titles + quantified cases e.g. ~$55M premium, hand-written llms.txt with flat-rate pricing model, calculators), Riskonnect (named Municipal Association of SC quote, buying guide + RFP template, FAQ, Platform Security page with SOC 2 Type 2; G2 35 reviews), Insly (pricing tiers by segment, custom quotes - no figures), Socotra (ISO 27001, SOC 1 T2 security page; 2021 Gartner MQ Visionary) / hx (SOC 2 + ISO 27001 on homepage), Vertafore MGA Systems (SoftwareApplication + FAQPage schema). Fact-checked 6 Oct 2026: data/factcheck_external.md. DICEUS's Gartner 5/5 and Clutch 4.9 are company-level ratings of the services business."''',
  '''"Розбір конкурентів (data/competitor_teardown.md): Luzern Risk (4 анонімні відгуки з посадами + кейси з цифрами, напр. ~$55M премій; ручний llms.txt з моделлю flat rate; калькулятори), Riskonnect (іменна цитата Municipal Association of SC, buying guide + RFP-шаблон, FAQ, сторінка Platform Security з SOC 2 Type 2; G2 — 35 відгуків), Insly (тарифи за сегментами, ціни за запитом), Socotra (ISO 27001, SOC 1 T2; Gartner MQ Visionary 2021) / hx (SOC 2 + ISO 27001 на головній), Vertafore MGA Systems (schema SoftwareApplication + FAQPage). Факт-чек 6.10.2026: data/factcheck_external.md. Рейтинги DICEUS Gartner 5/5 і Clutch 4.9 — оцінки компанії як сервісного бізнесу, а не продуктів."'''),
 ('["Feature depth for captives", "Strong", "Medium", "Low", "n/a", "n/a"]', '["Глибина функцій для captive", "Сильна", "Середня", "Низька", "н/з", "н/з"]'),
 ('["Customer proof with metrics", "No", "Anon. cases", "Named quote", "Named execs", "Logos + metrics"]', '["Докази клієнтів з цифрами", "Немає", "Анонім. кейси", "Іменна цитата", "Іменні керівники", "Логотипи + цифри"]'),
 ('["Product-level reviews", "0", "-", "G2: 35", "-", "Analyst"]', '["Відгуки саме про продукт", "0", "-", "G2: 35", "-", "Аналітики"]'),
 ('["Pricing model explained", "No", "Flat rate", "No", "Tiers, no prices", "No"]', '["Пояснена модель ціни", "Немає", "Flat rate", "Немає", "Тарифи без цін", "Немає"]'),
 ('["Security / trust page", "No", "-", "SOC 2 page", "-", "ISO 27001, SOC"]', '["Сторінка безпеки / довіри", "Немає", "-", "Сторінка SOC 2", "-", "ISO 27001, SOC"]'),
 ('["Buyer assets (guide, RFP, calculator)", "No", "Calculators", "Guide + RFP", "Glossary", "Docs"]', '["Матеріали для покупця", "Немає", "Калькулятори", "Гайд + RFP", "Глосарій", "Документація"]'),
 ('["FAQ + product schema", "No", "FAQ schema", "FAQ", "-", "-"]', '["FAQ + product schema", "Немає", "FAQ schema", "FAQ", "-", "-"]'),
 ('["Curated llms.txt", "PAS only", "Yes", "Auto", "No", "Auto / no"]', '["Ручний llms.txt", "Лише PAS", "Так", "Авто", "Немає", "Авто / немає"]'),
 ('const good = new Set(["Strong", "Yes", "Anon. cases", "Named quote", "Named execs", "Logos + metrics", "Flat rate", "Tiers, no prices", "SOC 2 page", "Guide + RFP", "Calculators", "ISO 27001, SOC", "FAQ schema", "G2: 35", "Analyst"]);',
  'const good = new Set(["Сильна", "Так", "Анонім. кейси", "Іменна цитата", "Іменні керівники", "Логотипи + цифри", "Flat rate", "Тарифи без цін", "Сторінка SOC 2", "Гайд + RFP", "Калькулятори", "ISO 27001, SOC", "FAQ schema", "G2: 35", "Аналітики"]);'),
 ('const bad = new Set(["No", "0", "PAS only"]);', 'const bad = new Set(["Немає", "0", "Лише PAS"]);'),
 # 6
 ('"pivot_slide.json"', '"pivot_slide_ua.json"'),
 # 7
 ('"Where to compete: alternative risk first"', '"Де конкурувати: спершу alternative risk"'),
 ('"Priority score = 0.45 business relevance + 0.35 SEO feasibility + 0.20 demand evidence (volumes not available, so demand weighs least)"', '"Бал = 0,45 бізнес-релевантність + 0,35 SEO-досяжність + 0,20 ознаки попиту (обсягів немає, тож попит важить найменше)"'),
 ('"From 03_Search_Market_and_Opportunity.xlsx / Territories. Sensitivity check: with equal weights the top two (captive, RRG) and bottom two (services) do not change. PAS has the most demand but Oracle/Guidewire/G2 own the head terms - win its long tail (PAS for MGAs / captives / RRGs) instead."',
  '"З 03_Search_Market_and_Opportunity.xlsx / Territories. Перевірка чутливості: з рівними вагами топ-2 (captive, RRG) і низ-2 (послуги) не змінюються. У PAS найбільший попит, але head-запити тримають Oracle/Guidewire/G2 — вигравати треба довгий хвіст (PAS для MGA / captive / RRG)."'),
 ('const labels = ["Captive insurance & management", "Risk retention groups", "Insurance GL / accounting", "Policy administration (PAS)", "Self-insured & pools", "Broker & customer portals", "Data warehouse & analytics", "Group insurance", "MGA / program admin", "Claims management", "Insurance dev services", "Generic IT services"];',
  'const labels = ["Captive: страхування й управління", "Risk retention groups (RRG)", "Страховий GL / облік", "Policy administration (PAS)", "Self-insured і пули", "Брокерські та клієнтські портали", "Сховище даних і аналітика", "Групове страхування", "MGA / програмні адміністратори", "Управління збитками (claims)", "Розробка для страхування", "Загальні IT-послуги"];'),
 ('name: "Priority score"', 'name: "Бал пріоритету"'),
 ('"Win now"', '"Вигравати зараз"'),
 ('"Captive + RRG: DICEUS #1 in our sample, thin SERPs, VCIA partner (Jun 2026), ~262 US RRGs and 40 US captive domiciles"', '"Captive + RRG: DICEUS №1 у вибірці, слабка конкуренція, партнер VCIA (червень 2026), ~262 RRG і 40 доміцилів captive у США"'),
 ('"Win the long tail"', '"Вигравати довгий хвіст"'),
 ('"PAS, underwriting, reinsurance: segment variants (\\"for MGAs\\", \\"for captives\\") and reviews, not head terms owned by Guidewire, Oracle and G2"', '"PAS, андеррайтинг, перестрахування: сегментні варіанти («for MGAs», «for captives») і відгуки, а не head-запити Guidewire, Oracle і G2"'),
 # 8
 ('"The whitespace nobody owns yet"', '"Вільна ніша, яку ще ніхто не зайняв"'),
 ('"Gaps no competitor fills, from the teardown of 13 vendors"', '"Прогалини, які не закриває жоден конкурент (розбір 13 вендорів)"'),
 ('''"Luzern Risk raised $45M and is an AI-native captive MANAGER: it competes with DICEUS's buyers, so 'software-only platform for independent captive managers' is a real wedge. Origami and Riskonnect never mention captives on their homepages; Websure's captive page is ~250 words. No authoritative 'best captive management software' guide exists: the exact query returns directories (incl. DICEUS's own Capterra/GetApp listings) and thin aggregator listicles."''',
  '''"Luzern Risk залучив $45M і є AI-native captive-МЕНЕДЖЕРОМ: він конкурує з покупцями DICEUS, тому позиція «лише ПЗ для незалежних captive-менеджерів» — реальний клин. Origami і Riskonnect не згадують captive на головних; сторінка captive у Websure — ~250 слів. Авторитетного гайду «best captive management software» немає: за точним запитом лише каталоги (зокрема лістинги DICEUS на Capterra/GetApp) і слабкі агрегатори."'''),
 ('["Software-only for captive managers", "Luzern ($45M Series B) now runs captives itself and competes with the managers who would buy DICEUS. Position as the platform independent managers run on."]',
  '["Лише ПЗ для captive-менеджерів", "Luzern ($45M Series B) сам керує captive і конкурує з менеджерами — покупцями DICEUS. Позиція: платформа незалежних менеджерів."]'),
 ('["One captive + RRG + self-insured family", "Origami and Riskonnect treat captives as an RMIS sub-feature; their homepages never mention them."]',
  '["Родина captive + RRG + self-insured", "В Origami і Riskonnect captive — підфункція RMIS; на головних про них ані слова."]'),
 ('["RRG search is almost uncontested", "SERP = DICEUS, a 2022 press release and Ventiv-era pages. An RRG hub (LRRA, domiciles, NAIC calendar) can own the topic."]',
  '["Пошук по RRG майже без конкурентів", "У видачі — DICEUS, прес-реліз 2022 р. і сторінки часів Ventiv. Хаб про RRG (LRRA, доміцилі, календар NAIC) може забрати тему."]'),
 ('''["No category guide, no curated llms.txt", "No authoritative 'best captive management software' guide: only directories and thin aggregator lists. No captive software vendor has a fact-dense llms.txt."]''',
  '''["Немає гайду категорії і llms.txt", "Авторитетного гайду «best captive management software» немає — лише каталоги й слабкі агрегатори. Жоден вендор ПЗ для captive не має насиченого фактами llms.txt."]'''),
 # 9
 ('"Target architecture: products first, URLs kept"', '"Цільова архітектура: продукти першими, URL ті самі"'),
 ('"Hierarchy through navigation, hubs and links; services and content link up into products"', '"Ієрархія через навігацію, хаби та посилання; послуги й контент посилаються вгору на продукти"'),
 ('"Products hub /insurance/solutions/, Alternative Risk hub (AROP page), buyer pages for MGAs and self-insured groups. Captive managers, RRGs and brokers are served by their product pages to avoid self-cannibalisation. Generic services stay live but leave the primary nav until GSC/CRM show their value."',
  '"Хаб продуктів /insurance/solutions/, хаб Alternative Risk (сторінка AROP), сторінки покупців для MGA і self-insured груп. Captive-менеджерів, RRG і брокерів обслуговують їхні продуктові сторінки — щоб не канібалізувати самих себе. Загальні послуги лишаються, але виходять з головного меню, доки GSC/CRM не покажуть їхню цінність."'),
 ('"fig5_future_architecture.png"', '"fig5_future_architecture_ua.png"'),
 # 10
 ('"What changes on the site"', '"Що змінюється на сайті"'),
 ('"Concrete changes, each tied to evidence and a best-in-class example"', '"Конкретні зміни — кожна з доказом і прикладом найкращої практики"'),
 ('"Examples: Decerto keeps separate Products and Services menus on one domain; Luzern segment-first nav; Riskonnect PAS page (named quote, buying guide, RFP template, FAQ); Insly pricing tiers (custom quotes); Socotra/hx security pages; Vertafore SoftwareApplication schema."',
  '"Приклади: Decerto — окремі меню Products і Services на одному домені; Luzern — навігація за сегментами; сторінка PAS у Riskonnect (іменна цитата, buying guide, RFP-шаблон, FAQ); тарифи Insly (ціни за запитом); сторінки безпеки Socotra/hx; schema SoftwareApplication у Vertafore."'),
 ('["Area", "Today (fact)", "Change", "Model to copy"]', '["Зона", "Сьогодні (факт)", "Зміна", "Взірець"]'),
 ('["Homepage", "H1 \\"Custom software development company\\"", "Product-category H1, segment self-select, proof band, services strip", "Decerto, Luzern"]', '["Головна", "H1 «Custom software development company»", "H1 з продуктовою категорією, вибір сегмента, смуга доказів, блок послуг", "Decerto, Luzern"]'),
 ('["Navigation", "~300 links, services-dominant mega-menu", "Products · Alternative risk · Buyers · Services · Resources; 30-40 menu links (<=120 links/page)", "Luzern, Insly"]', '["Навігація", "~300 посилань, мегаменю з перевагою послуг", "Продукти · Alt-risk · Покупці · Послуги · Ресурси; 30-40 пунктів меню (≤120 посилань/стор.)", "Luzern, Insly"]'),
 ('["Product pages", "Modules + benefits only", "Who it\'s for, video, integrations, proof, pricing model, FAQ, security", "Riskonnect, Vertafore"]', '["Продуктові сторінки", "Лише модулі + переваги", "Для кого, відео, інтеграції, докази, модель ціни, FAQ, безпека", "Riskonnect, Vertafore"]'),
 ('["Captive pages", "Noindex; two pages target the same audience", "Fix; managers vs owners split; spec in 04 App. A", "-"]', '["Сторінки captive", "Noindex; дві сторінки цілять в одну аудиторію", "Виправити; розділити менеджерів і власників; ТЗ у 04, дод. A", "-"]'),
 ('["Proof", "Company-level Gartner / Clutch ratings", "2-3 alt-risk case studies; 10+ product reviews", "Luzern, Riskonnect"]', '["Докази", "Рейтинги Gartner / Clutch на рівні компанії", "2-3 кейси alt-risk; 10+ відгуків про продукти", "Luzern, Riskonnect"]'),
 ('["New pages", "None", "/trust/, /pricing/ (model), RRG hub, comparison, RFP template", "Socotra, Insly, Riskonnect"]', '["Нові сторінки", "Немає", "/trust/, /pricing/ (модель), хаб RRG, порівняння, RFP-шаблон", "Socotra, Insly, Riskonnect"]'),
 ('["AI readiness", "No product schema; llms.txt = PAS", "SoftwareApplication + FAQ schema; curated llms.txt; Wikidata", "Vertafore, Luzern"]', '["Готовність до AI", "Немає product schema; llms.txt = PAS", "SoftwareApplication + FAQ schema; ручний llms.txt; Wikidata", "Vertafore, Luzern"]'),
 ('colW: [1.7, 3.4, 4.9, 2.1], rowH: 0.6', 'colW: [1.95, 3.3, 4.75, 2.1], rowH: 0.6'),
 # 11
 ('"AI search: own the captive and RRG answer"', '"AI-пошук: стати відповіддю про captive і RRG"'),
 ('"Brands named across 16 unbranded prompts (Claude + web search, 1 run each, directional)"', '"Бренди, названі в 16 небрендових запитах (Claude + веб-пошук, 1 прогін, орієнтовно)"'),
 ('''"Broad answers are assembled from analyst lists (Celent, Datos), G2/Capterra category pages and listicles - DICEUS is in none. 'What is DICEUS?' resolved to homonyms (no Wikidata). Listings surfaced without the brand name and with 0 reviews. ChatGPT, Perplexity and Google AI Overviews: not measured yet (panel v2 in days 5-20)."''',
  '''"Широкі відповіді збираються зі списків аналітиків (Celent, Datos), категорій G2/Capterra і листиклів — DICEUS немає в жодному. На «What is DICEUS?» модель видала омоніми (немає Wikidata). Лістинги з'являлися без назви бренду і з 0 відгуків. ChatGPT, Perplexity і Google AI Overviews ще не виміряні (панель v2 — дні 5-20)."'''),
 ('name: "Prompts naming the brand"', 'name: "Запитів із брендом"'),
 ('const lev = [["Be indexable", "Fix noindex on the pages that win today"], ["Carry the brand", "\\"DICEUS Captive Management Platform\\" on every listing"], ["Be cited by third parties", "Product reviews, Celent VendorMatch, captive trade press"], ["Be easy to quote", "SoftwareApplication + FAQ schema, curated llms.txt, Wikidata, pricing model"]];',
  'const lev = [["Бути в індексі", "Прибрати noindex зі сторінок, що вже виграють"], ["Нести бренд", "«DICEUS Captive Management Platform» у кожному лістингу"], ["Бути цитованим іншими", "Відгуки, Celent VendorMatch, галузеві медіа captive"], ["Бути зручним для цитування", "SoftwareApplication + FAQ schema, llms.txt, Wikidata, модель ціни"]];'),
 # 12
 ('"90 days: fix, reposition, prove"', '"90 днів: виправити, перепозиціонувати, довести"'),
 ('"Destructive changes (redirects, merges, pruning) only after GSC/CRM evidence"', '"Руйнівні зміни (редиректи, злиття, видалення) — лише після доказів із GSC/CRM"'),
 ('"Full plan with owners, dependencies and Definition of Done: 05_90_Day_Execution_Plan.xlsx (32 tasks). Governance: baseline + change log + 14-day check + rollback for every risky change."',
  '"Повний план із власниками, залежностями та Definition of Done: 05_90_Day_Execution_Plan.xlsx (32 задачі). Правила: базова лінія + журнал змін + перевірка через 14 днів + відкат для кожної ризикової зміни."'),
 ('["Days 1-30", "Fix · baseline · decide", CORAL, ["Remove noindex + deploy guardrail", "Connect GSC, GA4, CRM; baseline per URL", "Product truth table (what is a sellable SKU)", "Query-ownership map: one URL per cluster", "Rebuild Captive Management page (spec)", "Brand directory listings; start review drive", "AI panel v2 across 4 engines"]]',
  '["Дні 1-30", "Виправити · виміряти · вирішити", CORAL, ["Прибрати noindex + захист при деплої", "GSC, GA4, CRM; база по кожному URL", "Таблиця правди: що є продуктом", "Карта запитів: 1 URL на кластер", "Нова сторінка Captive Management (ТЗ)", "Бренд у лістингах; збір відгуків", "AI-панель v2 у 4 системах"]]'),
 ('["Days 31-60", "Reposition · build", NAVY, ["Homepage in 2 GSC-gated steps", "Nav v2: products first, 30-40 menu links", "Alternative Risk hub + self-insured page", "+ contextual links from 86 insurance posts", "/trust/ and /pricing/ (model) pages", "Comparison page + RFP template", "Wikidata entity; trade-press pitch"]]',
  '["Дні 31-60", "Перепозиціонувати · будувати", NAVY, ["Головна у 2 кроки з контролем GSC", "Меню v2: продукти першими, 30-40 пунктів", "Хаб Alt-Risk + сторінка self-insured", "Посилання з 86 страхових постів", "Сторінки /trust/ і /pricing/ (модель)", "Порівняння + RFP-шаблон", "Wikidata; пітч галузевим медіа"]]'),
 ('["Days 61-90", "Validate · scale", TEAL, ["MGA & program administrator page", "Merge overlaps only where GSC proves it", "Claims / feature pages only if validated", "Case-study archives noindex if 0 traffic", "Weekly automated crawl + GSC + AI digest", "Day-90 review and re-prioritisation", ""]]',
  '["Дні 61-90", "Перевірити · масштабувати", TEAL, ["Сторінка для MGA і програмних адміністраторів", "Злиття — лише де доведе GSC", "Claims / функції — після перевірки", "Noindex архівів кейсів, якщо 0 трафіку", "Щотижневий автозвіт: краул + GSC + AI", "Огляд на 90-й день, нові пріоритети", ""]]'),
 # 13
 ('"What we won\'t do yet, what we need, how we\'ll measure"', '"Чого поки не робимо, що потрібно, як міряємо"'),
 ('"Evidence before irreversible moves"', '"Спершу докази, потім незворотні кроки"'),
 ('"Not yet: (1) pruning ~190 generic service pages - their traffic and leads are unknown; (2) moving products to a new /products/ URL folder - equity and directory links at risk, no evidence the path hurts; (3) merging the two captive pages or overlapping service pages - need GSC query-by-page data."',
  '"Поки ні: (1) видаляти ~190 сторінок загальних послуг — їхній трафік і ліди невідомі; (2) переносити продукти в нову папку /products/ — під загрозою вага й посилання з каталогів, доказів шкоди поточного шляху немає; (3) зливати дві сторінки captive чи перетини послуг — потрібні дані GSC «запит × сторінка»."'),
 ('["Not yet (validate first)", CORAL, ["Prune or redirect the ~190 generic service pages", "Move products to a new /products/ URL folder", "Merge the two captive pages or service overlaps"]]',
  '["Поки ні (спершу перевірка)", CORAL, ["Видаляти чи редиректити ~190 сторінок загальних послуг", "Переносити продукти в нову папку /products/", "Зливати дві сторінки captive чи перетини послуг"]]'),
 ('["What we need from DICEUS", NAVY, ["GSC, GA4, CRM and Cloudflare log access", "Product truth table: what is sellable today", "One referenceable US alt-risk customer", "Security facts (ISO / SOC status)"]]',
  '["Що потрібно від DICEUS", NAVY, ["Доступ до GSC, GA4, CRM і логів Cloudflare", "Таблиця правди: що продається вже сьогодні", "Один референсний клієнт alt-risk у США", "Факти про безпеку (статус ISO / SOC)"]]'),
 ('["KPIs at day 90", TEAL, ["23/23 product pages indexed (now 20/23)", "Product in-content links: median 24 to 60+", "AI share of voice: 2/16 to 5/16+ (Claude)", "5+ published product reviews (now 0)", "Alt-risk impressions and demos vs baseline"]]',
  '["KPI на 90-й день", TEAL, ["23/23 продуктових сторінок в індексі (зараз 20/23)", "Посилання в тексті на продукти: медіана 24 → 60+", "Частка голосу в AI: 2/16 → 5/16+ (Claude)", "5+ відгуків про продукти (зараз 0)", "Покази alt-risk і демо відносно бази"]]'),
 # 14
 ('"First step: fix three tags this week"', '"Перший крок: виправити три теги цього тижня"'),
 ('"Then make products the strongest pages on diceus.com, and make DICEUS the answer for captive and RRG software in search and AI."', '"Далі — зробити продукти найсильнішими сторінками diceus.com, а DICEUS — відповіддю про ПЗ для captive і RRG у пошуку та AI."'),
 ('"Close on the decision: approve days 1-30 (fix, data access, product truth table, captive page rebuild)."', '"Завершити рішенням: затвердити дні 1-30 (виправлення, доступ до даних, таблиця правди продуктів, перебудова сторінки captive)."'),
 ('"DICEUS_SEO_AI_Search_micro_deck.pptx"', '"DICEUS_SEO_AI_Search_micro_deck_UA.pptx"'),
]
missing = [a for a, b in R if a not in s]
assert not missing, missing
for a, b in R:
    s = s.replace(a, b)
open('build_deck_ua.js', 'w', encoding='utf8').write(s)
print('UA script written,', len(R), 'replacements')
